### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by michelleyun98** [michelleyun98/bechdel#2]
# Tasks
- [ ] Docstrings for all functions
- [ ] Documentation for source code
- [ ] Unit tests
- [ ] Information about the format, metadata
## Update readme with following: 
- [ ]  Link to the source of the corpus and a link to the location of your collected corpus (either on your repo, or externally)
- [ ] Information about the format it is stored in (including metadata)
- [ ] total number of documents
- [ ] total amount of text (in words, ideally, though for instance characters would be acceptable for Chinese)
- [ ] Any known problems with the corpus (e.g. duplicates, noise)
